In [3]:
import numpy as np
import pandas as pd
import tensorflow as tf

# Data preprocessing

In [5]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [6]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [7]:
print(y)

[1 0 1 ... 1 1 0]


## Label Encoding the "Gender" column

In [8]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [9]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


## One Hot Encoding the "Geography" column

In [10]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [11]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


## Splitting the dataset

In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

## Feature Scaling

In [14]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

# Building the ANN

In [15]:
ann = tf.keras.models.Sequential()

2024-02-12 13:50:58.155796: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:901] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2024-02-12 13:50:58.156598: W tensorflow/core/common_runtime/gpu/gpu_device.cc:2256] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...


In [16]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [17]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [18]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# Training the ANN

In [19]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [20]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 1s 888us/step - loss: 0.6573 - accuracy: 0.6261
Epoch 2/100
250/250 [==============================] - 0s 857us/step - loss: 0.4468 - accuracy: 0.8176
Epoch 3/100
250/250 [==============================] - 0s 859us/step - loss: 0.4197 - accuracy: 0.8250
Epoch 4/100
250/250 [==============================] - 0s 903us/step - loss: 0.4104 - accuracy: 0.8270
Epoch 5/100
250/250 [==============================] - 0s 890us/step - loss: 0.4048 - accuracy: 0.8271
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4003 - accuracy: 0.8292
Epoch 7/100
250/250 [==============================] - 0s 987us/step - loss: 0.3967 - accuracy: 0.8304
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3934 - accuracy: 0.8317
Epoch 9/100
250/250 [==============================] - 0s 871us/step - loss: 0.3903 - accuracy: 0.8321
Epoch 10/100
250/250 [==============================] - 0s 859us/step - loss:

Epoch 80/100
250/250 [==============================] - 0s 850us/step - loss: 0.3367 - accuracy: 0.8629
Epoch 81/100
250/250 [==============================] - 0s 897us/step - loss: 0.3368 - accuracy: 0.8624
Epoch 82/100
250/250 [==============================] - 0s 917us/step - loss: 0.3362 - accuracy: 0.8654
Epoch 83/100
250/250 [==============================] - 0s 952us/step - loss: 0.3362 - accuracy: 0.8650
Epoch 84/100
250/250 [==============================] - 0s 963us/step - loss: 0.3367 - accuracy: 0.8635
Epoch 85/100
250/250 [==============================] - 0s 949us/step - loss: 0.3368 - accuracy: 0.8626
Epoch 86/100
250/250 [==============================] - 0s 935us/step - loss: 0.3363 - accuracy: 0.8635
Epoch 87/100
250/250 [==============================] - 0s 886us/step - loss: 0.3366 - accuracy: 0.8631
Epoch 88/100
250/250 [==============================] - 0s 802us/step - loss: 0.3364 - accuracy: 0.8634
Epoch 89/100
250/250 [==============================] - 0s 1ms/s

# Predict test set result

In [21]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

63/63 [==============================] - 0s 641us/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


# Confusion matrix

In [22]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1524   71]
 [ 204  201]]


0.8625